### GET
GET http://localhost:5000/basis HTTP/1.1
yope: myYope
hurra: hip


### GET async
GET http://localhost:5000/basis/async HTTP/1.1


### GET by id
GET http://localhost:5000/basis/car/17 HTTP/1.1



### GET mit express Response
GET http://localhost:5000/basis/custom HTTP/1.1



### POST
POST  http://localhost:5000/basis HTTP/1.1
content-type: application/json

{
    "name": "HundeEy",
    "ps": 265
}


### Redirect
GET  http://localhost:5000/basis/redirect HTTP/1.1

# Error -------------------------------------------------

### Error - new Error()
GET  http://localhost:5000/error/unrecognized HTTP/1.1

### Error - new Error() - Catch
GET  http://localhost:5000/error/unrecognized-catch HTTP/1.1


### Error - new HttpException()
GET  http://localhost:5000/error/httperror HTTP/1.1

### Error - From Nest Inheritance
GET  http://localhost:5000/error/inheritanceerror HTTP/1.1

### Error - new LowBatteryException()
GET  http://localhost:5000/error/customerror HTTP/1.1

### Error - new Filter
GET  http://localhost:5000/error/filtererror HTTP/1.1

# Pipe -------------------------------------------------

### Pipe - ParseIntPipe
GET http://localhost:5000/pipe/p/nonumber HTTP/1.1

### Pipe - Default value pipe
GET http://localhost:5000/pipe/defaultvalue?bonus=true HTTP/1.1

### Pipe - CustomError pipe
GET http://localhost:5000/pipe/customerror/nonumber HTTP/1.1

### Pipe - Custom pipe using method param
POST http://localhost:5000/pipe/body-from-param/nobev HTTP/1.1
content-type: application/json

{
    "name": "Trabbi 701",
    "type": "PHEV"
}

### Pipe - Custom pipe using method decorator
POST http://localhost:5000/pipe/body-from-method-decorator/nobev HTTP/1.1
content-type: application/json

{
    "name": "Trabbi 701",
    "type": "PHEV"
}

### Pipe - Custom pipe using class decorator
POST http://localhost:5000/pipe/body-from-class-decorator/nobev HTTP/1.1
content-type: application/json

{
    "name": "Trabbi 701",
    "type": "PHEV"
}

### Pipe - Custom pipe using class validator
POST http://localhost:5000/pipe/body-from-class-validator/no-ps HTTP/1.1
content-type: application/json

{
    "name": "Trabbi 701",
    "type": "BEV",
    "ps": "000012"
}

### Pipe - Custom pipe using built in ValidationPipe and class validator
POST http://localhost:5000/pipe/body-from-class-validator-with-built-in-validation HTTP/1.1
content-type: application/json

{
    "name": "Trabbi 701",
    "type": "NO enum value",
    "ps": 200
}

# Guard --------------------------------------------------------
### Guard - Ist möglich
GET http://localhost:5000/guard/auth HTTP/1.1
x-token: 007

### Guard - Ist NICHT möglich
GET http://localhost:5000/guard/auth HTTP/1.1
x-token: 000

### Guard - Rolle mit SetMetaData
GET http://localhost:5000/guard/role/set-meta-data HTTP/1.1
x-user: James

### Guard - Rolle mit SetMetaData
GET http://localhost:5000/guard/role/set-meta-data HTTP/1.1
x-user: Taxy

### Guard - Rolle mit custom decorator
GET http://localhost:5000/guard/role/custom-decorator HTTP/1.1
x-user: Taxy

### Interceptor - log

GET http://localhost:5000/interceptor/log HTTP/1.1

### Interceptor - Error
GET http://localhost:5000/interceptor/error HTTP/1.1

### Interceptor - Timeout
GET http://localhost:5000/interceptor/timeout HTTP/1.1