### GET
GET http://localhost:5000/basis HTTP/1.1
yope: myYope
hurra: hip


### GET mit express Response

GET http://localhost:5000/basis/custom HTTP/1.1


### POST
POST  http://localhost:5000/basis HTTP/1.1
content-type: application/json

{
    "name": "HundeEy",
    "ps": 265
}