### GET
GET http://localhost:5000/basis HTTP/1.1
yope: myYope
hurra: hip 


### GET async
GET http://localhost:5000/basis/async HTTP/1.1


### GET by id
GET http://localhost:5000/basis/car/17 HTTP/1.1



### GET mit express Response
GET http://localhost:5000/basis/custom HTTP/1.1



### POST
POST  http://localhost:5000/basis HTTP/1.1
content-type: application/json

{
    "name": "HundeEy",
    "ps": 265
}


### Redirect
GET  http://localhost:5000/basis/redirect HTTP/1.1
content-type: application/json

# Error -------------------------------------------------

### Error - new Error()
GET  http://localhost:5000/error/unrecognized HTTP/1.1
content-type: application/json


### Error - new HttpException()
GET  http://localhost:5000/error/httperror HTTP/1.1
content-type: application/json


### Error - new LowBatteryException()
GET  http://localhost:5000/error/customerror HTTP/1.1
content-type: application/json

### Error - new Filter
GET  http://localhost:5000/error/filtererror HTTP/1.1
content-type: application/json


# Pipe -------------------------------------------------

### Pipe - ParseIntPipe
GET  http://localhost:5000/pipe/p/nonumber HTTP/1.1
content-type: application/json